package com.chibuisi.dailyinsightservice.springsecapp.model;

public enum Role {
    ROLE_USER,
    ROLE_MODERATOR,
    ROLE_ADMIN,
    ROLE_COACH,
    ROLE_DEVELOPER,
    ROLE_CLIENT,
    ROLE_CAN_ADD_TOPIC,
    ROLE_CAN_UPDATE_TOPIC,
    ROLE_CAN_REMOVE_TOPIC,
    ROLE_CAN_ADD_COACH,
    ROLE_CAN_UPDATE_COACH,
    ROLE_CAN_REMOVE_COACH,
    ROLE_CAN_MANAGE_COACH,
    ROLE_CREATE_ARTICLE,
    ROLE_DELETE_ARTICLE,
    ROLE_UPDATE_ARTICLE
}
