version: "3.4"
services:
  mysql:
    container_name: minor-insights-mysql
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ #must be set in .env
    ports:
    - 3310:3306
    expose:
      - 3310
    volumes:
    - mysql:/c/mysql

  pubsub:
    image: google/cloud-sdk:emulators
    command:
      - gcloud
      - --quiet
      - beta
      - emulators
      - pubsub
      - start
      - --project=is-minor-insights-dev
      - --host-port=0.0.0.0:8681
    container_name: minor-insights-pubsub
    ports:
    - 8681:8681
    environment:
      PUBSUB_PROJECT1: "is-minor-insights-dev,email:emailsubscription"
      PUBSUB_EMULATOR_HOST: "localhost:8681"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8681" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 2m

  create-topics-and-subscriptions:
    image: alpine/curl
    container_name: create-topics-and-subscriptions
    volumes:
      - "./bin/create-topics-and-subscriptions.sh:/usr/local/bin/create-topics-and-subscriptions"
    command: "create-topics-and-subscriptions"
    depends_on:
      - pubsub

#  pubsub:
#    container_name: di-pubsub
#    image: messagebird/gcloud-pubsub-emulator:latest
#    ports:
#    - 8681:8681
#    environment:
#      PUBSUB_PROJECT1: "is-minor-insights-dev,email:emailsubscription"
#      PUBSUB_EMULATOR_HOST: "localhost:8681"

#  redis:
#    container_name: di-redis
#    image: redis:5.0.3-alpine
#    ports:
#    - 6379:6379
#
#
#  datastore:
#    container_name: di-datastore
#    image: gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
#    command: ["/bin/sh", "-c", "gcloud beta emulators datastore start --data-dir=/opt/data --host-port=0.0.0.0:8081 --consistency=1.0 --store-on-disk --project=is-daily-insights-dev"]
#    ports:
#    - 18081:8081
#    environment:
#      DATASTORE_PROJECT_ID: "is-minor-insights-dev"
#      DATASTORE_LISTEN_ADDRESS: "0.0.0.0"
#      DATASTORE_OPTIONS: "--consistency=1.0 --no-store-on-disk"
volumes:
  mysql:
  pubsub:
